export enum FicheStatut {
  EN_ATTENTE = 'EN_ATTENTE',
  EN_COURS = 'EN_COURS',
  ARRIVE_GARE = 'ARRIVE_GARE',
  EN_TRANSIT = 'EN_TRANSIT',
  ARRIVE_DESTINATION = 'ARRIVE_DESTINATION',
  FINALISEE = 'FINALISEE',
  CLOTUREE = 'CLOTUREE',
  ANNULEE = 'ANNULEE',
}